source 'https://rubygems.org'

gem 'activerecord'
gem 'mysql2'
gem 'puma'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-param'
gem 'pry'
gem 'rack-contrib'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'database_cleaner-active_record'
end
